// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerCommand.proto

package com.netty.model.protobuf;

public final class ServerCommand {
  private ServerCommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.netty.model.protobuf.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *登录请求
     * </pre>
     *
     * <code>LOGIN_REQ = 0;</code>
     */
    LOGIN_REQ(0),
    /**
     * <pre>
     *登录回复
     * </pre>
     *
     * <code>LOGIN_RESP = 1;</code>
     */
    LOGIN_RESP(1),
    /**
     * <pre>
     *心跳检测,一般客户端需要2秒发送一次心跳到服务器端以维持在线状态
     * </pre>
     *
     * <code>HEARTBEAT = 2;</code>
     */
    HEARTBEAT(2),
    /**
     * <pre>
     *测试消息
     * </pre>
     *
     * <code>SENDMESSAGE = 3;</code>
     */
    SENDMESSAGE(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *登录请求
     * </pre>
     *
     * <code>LOGIN_REQ = 0;</code>
     */
    public static final int LOGIN_REQ_VALUE = 0;
    /**
     * <pre>
     *登录回复
     * </pre>
     *
     * <code>LOGIN_RESP = 1;</code>
     */
    public static final int LOGIN_RESP_VALUE = 1;
    /**
     * <pre>
     *心跳检测,一般客户端需要2秒发送一次心跳到服务器端以维持在线状态
     * </pre>
     *
     * <code>HEARTBEAT = 2;</code>
     */
    public static final int HEARTBEAT_VALUE = 2;
    /**
     * <pre>
     *测试消息
     * </pre>
     *
     * <code>SENDMESSAGE = 3;</code>
     */
    public static final int SENDMESSAGE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN_REQ;
        case 1: return LOGIN_RESP;
        case 2: return HEARTBEAT;
        case 3: return SENDMESSAGE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ServerCommand.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.netty.model.protobuf.MessageType)
  }

  public interface CommandRouterModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.netty.model.protobuf.CommandRouterModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *提示信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    String getMessage();
    /**
     * <pre>
     *提示信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *目标客户端
     * </pre>
     *
     * <code>string toClientId = 3;</code>
     */
    String getToClientId();
    /**
     * <pre>
     *目标客户端
     * </pre>
     *
     * <code>string toClientId = 3;</code>
     */
    com.google.protobuf.ByteString
        getToClientIdBytes();

    /**
     * <pre>
     *源服务器
     * </pre>
     *
     * <code>string fromServer = 4;</code>
     */
    String getFromServer();
    /**
     * <pre>
     *源服务器
     * </pre>
     *
     * <code>string fromServer = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromServerBytes();

    /**
     * <pre>
     *目标服务器  
     * </pre>
     *
     * <code>string toServer = 5;</code>
     */
    String getToServer();
    /**
     * <pre>
     *目标服务器  
     * </pre>
     *
     * <code>string toServer = 5;</code>
     */
    com.google.protobuf.ByteString
        getToServerBytes();
  }
  /**
   * Protobuf type {@code com.netty.model.protobuf.CommandRouterModel}
   */
  public  static final class CommandRouterModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.netty.model.protobuf.CommandRouterModel)
      CommandRouterModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandRouterModel.newBuilder() to construct.
    private CommandRouterModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandRouterModel() {
      message_ = "";
      toClientId_ = "";
      fromServer_ = "";
      toServer_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommandRouterModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              toClientId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              fromServer_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              toServer_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerCommand.internal_static_com_netty_model_protobuf_CommandRouterModel_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerCommand.internal_static_com_netty_model_protobuf_CommandRouterModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommandRouterModel.class, Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile Object message_;
    /**
     * <pre>
     *提示信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *提示信息
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOCLIENTID_FIELD_NUMBER = 3;
    private volatile Object toClientId_;
    /**
     * <pre>
     *目标客户端
     * </pre>
     *
     * <code>string toClientId = 3;</code>
     */
    public String getToClientId() {
      Object ref = toClientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toClientId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *目标客户端
     * </pre>
     *
     * <code>string toClientId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToClientIdBytes() {
      Object ref = toClientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toClientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMSERVER_FIELD_NUMBER = 4;
    private volatile Object fromServer_;
    /**
     * <pre>
     *源服务器
     * </pre>
     *
     * <code>string fromServer = 4;</code>
     */
    public String getFromServer() {
      Object ref = fromServer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        fromServer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *源服务器
     * </pre>
     *
     * <code>string fromServer = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromServerBytes() {
      Object ref = fromServer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        fromServer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOSERVER_FIELD_NUMBER = 5;
    private volatile Object toServer_;
    /**
     * <pre>
     *目标服务器  
     * </pre>
     *
     * <code>string toServer = 5;</code>
     */
    public String getToServer() {
      Object ref = toServer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toServer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *目标服务器  
     * </pre>
     *
     * <code>string toServer = 5;</code>
     */
    public com.google.protobuf.ByteString
        getToServerBytes() {
      Object ref = toServer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toServer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!getToClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, toClientId_);
      }
      if (!getFromServerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromServer_);
      }
      if (!getToServerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, toServer_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!getToClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, toClientId_);
      }
      if (!getFromServerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromServer_);
      }
      if (!getToServerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, toServer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CommandRouterModel)) {
        return super.equals(obj);
      }
      CommandRouterModel other = (CommandRouterModel) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getToClientId()
          .equals(other.getToClientId());
      result = result && getFromServer()
          .equals(other.getFromServer());
      result = result && getToServer()
          .equals(other.getToServer());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TOCLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getToClientId().hashCode();
      hash = (37 * hash) + FROMSERVER_FIELD_NUMBER;
      hash = (53 * hash) + getFromServer().hashCode();
      hash = (37 * hash) + TOSERVER_FIELD_NUMBER;
      hash = (53 * hash) + getToServer().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CommandRouterModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandRouterModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandRouterModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandRouterModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandRouterModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandRouterModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandRouterModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandRouterModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandRouterModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CommandRouterModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandRouterModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandRouterModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CommandRouterModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.netty.model.protobuf.CommandRouterModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.netty.model.protobuf.CommandRouterModel)
        CommandRouterModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerCommand.internal_static_com_netty_model_protobuf_CommandRouterModel_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerCommand.internal_static_com_netty_model_protobuf_CommandRouterModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommandRouterModel.class, Builder.class);
      }

      // Construct using com.netty.model.protobuf.ServerCommand.CommandRouterModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        message_ = "";

        toClientId_ = "";

        fromServer_ = "";

        toServer_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServerCommand.internal_static_com_netty_model_protobuf_CommandRouterModel_descriptor;
      }

      @Override
      public CommandRouterModel getDefaultInstanceForType() {
        return CommandRouterModel.getDefaultInstance();
      }

      @Override
      public CommandRouterModel build() {
        CommandRouterModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CommandRouterModel buildPartial() {
        CommandRouterModel result = new CommandRouterModel(this);
        result.message_ = message_;
        result.toClientId_ = toClientId_;
        result.fromServer_ = fromServer_;
        result.toServer_ = toServer_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommandRouterModel) {
          return mergeFrom((CommandRouterModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommandRouterModel other) {
        if (other == CommandRouterModel.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getToClientId().isEmpty()) {
          toClientId_ = other.toClientId_;
          onChanged();
        }
        if (!other.getFromServer().isEmpty()) {
          fromServer_ = other.fromServer_;
          onChanged();
        }
        if (!other.getToServer().isEmpty()) {
          toServer_ = other.toServer_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CommandRouterModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CommandRouterModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object message_ = "";
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private Object toClientId_ = "";
      /**
       * <pre>
       *目标客户端
       * </pre>
       *
       * <code>string toClientId = 3;</code>
       */
      public String getToClientId() {
        Object ref = toClientId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toClientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *目标客户端
       * </pre>
       *
       * <code>string toClientId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToClientIdBytes() {
        Object ref = toClientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toClientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目标客户端
       * </pre>
       *
       * <code>string toClientId = 3;</code>
       */
      public Builder setToClientId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toClientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标客户端
       * </pre>
       *
       * <code>string toClientId = 3;</code>
       */
      public Builder clearToClientId() {
        
        toClientId_ = getDefaultInstance().getToClientId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标客户端
       * </pre>
       *
       * <code>string toClientId = 3;</code>
       */
      public Builder setToClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toClientId_ = value;
        onChanged();
        return this;
      }

      private Object fromServer_ = "";
      /**
       * <pre>
       *源服务器
       * </pre>
       *
       * <code>string fromServer = 4;</code>
       */
      public String getFromServer() {
        Object ref = fromServer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          fromServer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *源服务器
       * </pre>
       *
       * <code>string fromServer = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromServerBytes() {
        Object ref = fromServer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          fromServer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *源服务器
       * </pre>
       *
       * <code>string fromServer = 4;</code>
       */
      public Builder setFromServer(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromServer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *源服务器
       * </pre>
       *
       * <code>string fromServer = 4;</code>
       */
      public Builder clearFromServer() {
        
        fromServer_ = getDefaultInstance().getFromServer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *源服务器
       * </pre>
       *
       * <code>string fromServer = 4;</code>
       */
      public Builder setFromServerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromServer_ = value;
        onChanged();
        return this;
      }

      private Object toServer_ = "";
      /**
       * <pre>
       *目标服务器  
       * </pre>
       *
       * <code>string toServer = 5;</code>
       */
      public String getToServer() {
        Object ref = toServer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toServer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *目标服务器  
       * </pre>
       *
       * <code>string toServer = 5;</code>
       */
      public com.google.protobuf.ByteString
          getToServerBytes() {
        Object ref = toServer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toServer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目标服务器  
       * </pre>
       *
       * <code>string toServer = 5;</code>
       */
      public Builder setToServer(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toServer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标服务器  
       * </pre>
       *
       * <code>string toServer = 5;</code>
       */
      public Builder clearToServer() {
        
        toServer_ = getDefaultInstance().getToServer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目标服务器  
       * </pre>
       *
       * <code>string toServer = 5;</code>
       */
      public Builder setToServerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toServer_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.netty.model.protobuf.CommandRouterModel)
    }

    // @@protoc_insertion_point(class_scope:com.netty.model.protobuf.CommandRouterModel)
    private static final CommandRouterModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CommandRouterModel();
    }

    public static CommandRouterModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommandRouterModel>
        PARSER = new com.google.protobuf.AbstractParser<CommandRouterModel>() {
      @Override
      public CommandRouterModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandRouterModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandRouterModel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CommandRouterModel> getParserForType() {
      return PARSER;
    }

    @Override
    public CommandRouterModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommandModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.netty.model.protobuf.CommandModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发送的请求类型
     * </pre>
     *
     * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
     */
    int getMessageTypeValue();
    /**
     * <pre>
     *发送的请求类型
     * </pre>
     *
     * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
     */
    MessageType getMessageType();

    /**
     * <pre>
     *发送的数据，可以为任意类型
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    boolean hasData();
    /**
     * <pre>
     *发送的数据，可以为任意类型
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    com.google.protobuf.Any getData();
    /**
     * <pre>
     *发送的数据，可以为任意类型
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getDataOrBuilder();

    /**
     * <pre>
     *处理结果  1表示成功  非1表示失败 
     * </pre>
     *
     * <code>int32 result = 3;</code>
     */
    int getResult();

    /**
     * <pre>
     *提示信息
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    String getMessage();
    /**
     * <pre>
     *提示信息
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *请求的终端号
     * </pre>
     *
     * <code>string clientId = 5;</code>
     */
    String getClientId();
    /**
     * <pre>
     *请求的终端号
     * </pre>
     *
     * <code>string clientId = 5;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <pre>
     *服务器时间
     * </pre>
     *
     * <code>int64 serverTime = 6;</code>
     */
    long getServerTime();

    /**
     * <pre>
     *服务器之间转发信息
     * </pre>
     *
     * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
     */
    boolean hasDistributeData();
    /**
     * <pre>
     *服务器之间转发信息
     * </pre>
     *
     * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
     */
    CommandRouterModel getDistributeData();
    /**
     * <pre>
     *服务器之间转发信息
     * </pre>
     *
     * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
     */
    CommandRouterModelOrBuilder getDistributeDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.netty.model.protobuf.CommandModel}
   */
  public  static final class CommandModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.netty.model.protobuf.CommandModel)
      CommandModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandModel.newBuilder() to construct.
    private CommandModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandModel() {
      messageType_ = 0;
      result_ = 0;
      message_ = "";
      clientId_ = "";
      serverTime_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommandModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              result_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 48: {

              serverTime_ = input.readInt64();
              break;
            }
            case 58: {
              CommandRouterModel.Builder subBuilder = null;
              if (distributeData_ != null) {
                subBuilder = distributeData_.toBuilder();
              }
              distributeData_ = input.readMessage(CommandRouterModel.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(distributeData_);
                distributeData_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ServerCommand.internal_static_com_netty_model_protobuf_CommandModel_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ServerCommand.internal_static_com_netty_model_protobuf_CommandModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommandModel.class, Builder.class);
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <pre>
     *发送的请求类型
     * </pre>
     *
     * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     *发送的请求类型
     * </pre>
     *
     * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
     */
    public MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(messageType_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.Any data_;
    /**
     * <pre>
     *发送的数据，可以为任意类型
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <pre>
     *发送的数据，可以为任意类型
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public com.google.protobuf.Any getData() {
      return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
    }
    /**
     * <pre>
     *发送的数据，可以为任意类型
     * </pre>
     *
     * <code>.google.protobuf.Any data = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
      return getData();
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private int result_;
    /**
     * <pre>
     *处理结果  1表示成功  非1表示失败 
     * </pre>
     *
     * <code>int32 result = 3;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private volatile Object message_;
    /**
     * <pre>
     *提示信息
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public String getMessage() {
      Object ref = message_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *提示信息
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTID_FIELD_NUMBER = 5;
    private volatile Object clientId_;
    /**
     * <pre>
     *请求的终端号
     * </pre>
     *
     * <code>string clientId = 5;</code>
     */
    public String getClientId() {
      Object ref = clientId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *请求的终端号
     * </pre>
     *
     * <code>string clientId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERTIME_FIELD_NUMBER = 6;
    private long serverTime_;
    /**
     * <pre>
     *服务器时间
     * </pre>
     *
     * <code>int64 serverTime = 6;</code>
     */
    public long getServerTime() {
      return serverTime_;
    }

    public static final int DISTRIBUTEDATA_FIELD_NUMBER = 7;
    private CommandRouterModel distributeData_;
    /**
     * <pre>
     *服务器之间转发信息
     * </pre>
     *
     * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
     */
    public boolean hasDistributeData() {
      return distributeData_ != null;
    }
    /**
     * <pre>
     *服务器之间转发信息
     * </pre>
     *
     * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
     */
    public CommandRouterModel getDistributeData() {
      return distributeData_ == null ? CommandRouterModel.getDefaultInstance() : distributeData_;
    }
    /**
     * <pre>
     *服务器之间转发信息
     * </pre>
     *
     * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
     */
    public CommandRouterModelOrBuilder getDistributeDataOrBuilder() {
      return getDistributeData();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != MessageType.LOGIN_REQ.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (data_ != null) {
        output.writeMessage(2, getData());
      }
      if (result_ != 0) {
        output.writeInt32(3, result_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientId_);
      }
      if (serverTime_ != 0L) {
        output.writeInt64(6, serverTime_);
      }
      if (distributeData_ != null) {
        output.writeMessage(7, getDistributeData());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != MessageType.LOGIN_REQ.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getData());
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, result_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientId_);
      }
      if (serverTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, serverTime_);
      }
      if (distributeData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getDistributeData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CommandModel)) {
        return super.equals(obj);
      }
      CommandModel other = (CommandModel) obj;

      boolean result = true;
      result = result && messageType_ == other.messageType_;
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && (getResult()
          == other.getResult());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && (getServerTime()
          == other.getServerTime());
      result = result && (hasDistributeData() == other.hasDistributeData());
      if (hasDistributeData()) {
        result = result && getDistributeData()
            .equals(other.getDistributeData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerTime());
      if (hasDistributeData()) {
        hash = (37 * hash) + DISTRIBUTEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getDistributeData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CommandModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommandModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommandModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CommandModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CommandModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CommandModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CommandModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.netty.model.protobuf.CommandModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.netty.model.protobuf.CommandModel)
        CommandModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ServerCommand.internal_static_com_netty_model_protobuf_CommandModel_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ServerCommand.internal_static_com_netty_model_protobuf_CommandModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommandModel.class, Builder.class);
      }

      // Construct using com.netty.model.protobuf.ServerCommand.CommandModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        result_ = 0;

        message_ = "";

        clientId_ = "";

        serverTime_ = 0L;

        if (distributeDataBuilder_ == null) {
          distributeData_ = null;
        } else {
          distributeData_ = null;
          distributeDataBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ServerCommand.internal_static_com_netty_model_protobuf_CommandModel_descriptor;
      }

      @Override
      public CommandModel getDefaultInstanceForType() {
        return CommandModel.getDefaultInstance();
      }

      @Override
      public CommandModel build() {
        CommandModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CommandModel buildPartial() {
        CommandModel result = new CommandModel(this);
        result.messageType_ = messageType_;
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        result.result_ = result_;
        result.message_ = message_;
        result.clientId_ = clientId_;
        result.serverTime_ = serverTime_;
        if (distributeDataBuilder_ == null) {
          result.distributeData_ = distributeData_;
        } else {
          result.distributeData_ = distributeDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommandModel) {
          return mergeFrom((CommandModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommandModel other) {
        if (other == CommandModel.getDefaultInstance()) return this;
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (other.getServerTime() != 0L) {
          setServerTime(other.getServerTime());
        }
        if (other.hasDistributeData()) {
          mergeDistributeData(other.getDistributeData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CommandModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CommandModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int messageType_ = 0;
      /**
       * <pre>
       *发送的请求类型
       * </pre>
       *
       * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <pre>
       *发送的请求类型
       * </pre>
       *
       * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的请求类型
       * </pre>
       *
       * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
       */
      public MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(messageType_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *发送的请求类型
       * </pre>
       *
       * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
       */
      public Builder setMessageType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的请求类型
       * </pre>
       *
       * <code>.com.netty.model.protobuf.MessageType messageType = 1;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any data_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public com.google.protobuf.Any getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public Builder setData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public Builder setData(
          com.google.protobuf.Any.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public Builder mergeData(com.google.protobuf.Any value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public com.google.protobuf.Any.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : data_;
        }
      }
      /**
       * <pre>
       *发送的数据，可以为任意类型
       * </pre>
       *
       * <code>.google.protobuf.Any data = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      private int result_ ;
      /**
       * <pre>
       *处理结果  1表示成功  非1表示失败 
       * </pre>
       *
       * <code>int32 result = 3;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <pre>
       *处理结果  1表示成功  非1表示失败 
       * </pre>
       *
       * <code>int32 result = 3;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *处理结果  1表示成功  非1表示失败 
       * </pre>
       *
       * <code>int32 result = 3;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private Object message_ = "";
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public String getMessage() {
        Object ref = message_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder setMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *提示信息
       * </pre>
       *
       * <code>string message = 4;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private Object clientId_ = "";
      /**
       * <pre>
       *请求的终端号
       * </pre>
       *
       * <code>string clientId = 5;</code>
       */
      public String getClientId() {
        Object ref = clientId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *请求的终端号
       * </pre>
       *
       * <code>string clientId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求的终端号
       * </pre>
       *
       * <code>string clientId = 5;</code>
       */
      public Builder setClientId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求的终端号
       * </pre>
       *
       * <code>string clientId = 5;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求的终端号
       * </pre>
       *
       * <code>string clientId = 5;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private long serverTime_ ;
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>int64 serverTime = 6;</code>
       */
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>int64 serverTime = 6;</code>
       */
      public Builder setServerTime(long value) {
        
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>int64 serverTime = 6;</code>
       */
      public Builder clearServerTime() {
        
        serverTime_ = 0L;
        onChanged();
        return this;
      }

      private CommandRouterModel distributeData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          CommandRouterModel, CommandRouterModel.Builder, CommandRouterModelOrBuilder> distributeDataBuilder_;
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      public boolean hasDistributeData() {
        return distributeDataBuilder_ != null || distributeData_ != null;
      }
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      public CommandRouterModel getDistributeData() {
        if (distributeDataBuilder_ == null) {
          return distributeData_ == null ? CommandRouterModel.getDefaultInstance() : distributeData_;
        } else {
          return distributeDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      public Builder setDistributeData(CommandRouterModel value) {
        if (distributeDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          distributeData_ = value;
          onChanged();
        } else {
          distributeDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      public Builder setDistributeData(
          CommandRouterModel.Builder builderForValue) {
        if (distributeDataBuilder_ == null) {
          distributeData_ = builderForValue.build();
          onChanged();
        } else {
          distributeDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      public Builder mergeDistributeData(CommandRouterModel value) {
        if (distributeDataBuilder_ == null) {
          if (distributeData_ != null) {
            distributeData_ =
              CommandRouterModel.newBuilder(distributeData_).mergeFrom(value).buildPartial();
          } else {
            distributeData_ = value;
          }
          onChanged();
        } else {
          distributeDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      public Builder clearDistributeData() {
        if (distributeDataBuilder_ == null) {
          distributeData_ = null;
          onChanged();
        } else {
          distributeData_ = null;
          distributeDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      public CommandRouterModel.Builder getDistributeDataBuilder() {
        
        onChanged();
        return getDistributeDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      public CommandRouterModelOrBuilder getDistributeDataOrBuilder() {
        if (distributeDataBuilder_ != null) {
          return distributeDataBuilder_.getMessageOrBuilder();
        } else {
          return distributeData_ == null ?
              CommandRouterModel.getDefaultInstance() : distributeData_;
        }
      }
      /**
       * <pre>
       *服务器之间转发信息
       * </pre>
       *
       * <code>.com.netty.model.protobuf.CommandRouterModel distributeData = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CommandRouterModel, CommandRouterModel.Builder, CommandRouterModelOrBuilder>
          getDistributeDataFieldBuilder() {
        if (distributeDataBuilder_ == null) {
          distributeDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CommandRouterModel, CommandRouterModel.Builder, CommandRouterModelOrBuilder>(
                  getDistributeData(),
                  getParentForChildren(),
                  isClean());
          distributeData_ = null;
        }
        return distributeDataBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.netty.model.protobuf.CommandModel)
    }

    // @@protoc_insertion_point(class_scope:com.netty.model.protobuf.CommandModel)
    private static final CommandModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CommandModel();
    }

    public static CommandModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommandModel>
        PARSER = new com.google.protobuf.AbstractParser<CommandModel>() {
      @Override
      public CommandModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandModel> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CommandModel> getParserForType() {
      return PARSER;
    }

    @Override
    public CommandModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_model_protobuf_CommandRouterModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_model_protobuf_CommandRouterModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_netty_model_protobuf_CommandModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_netty_model_protobuf_CommandModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ServerCommand.proto\022\030com.netty.model.p" +
      "rotobuf\032\031google/protobuf/any.proto\"_\n\022Co" +
      "mmandRouterModel\022\017\n\007message\030\002 \001(\t\022\022\n\ntoC" +
      "lientId\030\003 \001(\t\022\022\n\nfromServer\030\004 \001(\t\022\020\n\010toS" +
      "erver\030\005 \001(\t\"\373\001\n\014CommandModel\022:\n\013messageT" +
      "ype\030\001 \001(\0162%.com.netty.model.protobuf.Mes" +
      "sageType\022\"\n\004data\030\002 \001(\0132\024.google.protobuf" +
      ".Any\022\016\n\006result\030\003 \001(\005\022\017\n\007message\030\004 \001(\t\022\020\n" +
      "\010clientId\030\005 \001(\t\022\022\n\nserverTime\030\006 \001(\003\022D\n\016d" +
      "istributeData\030\007 \001(\0132,.com.netty.model.pr" +
      "otobuf.CommandRouterModel*L\n\013MessageType" +
      "\022\r\n\tLOGIN_REQ\020\000\022\016\n\nLOGIN_RESP\020\001\022\r\n\tHEART" +
      "BEAT\020\002\022\017\n\013SENDMESSAGE\020\003B)\n\030com.netty.mod" +
      "el.protobufB\rServerCommandb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_com_netty_model_protobuf_CommandRouterModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_netty_model_protobuf_CommandRouterModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_model_protobuf_CommandRouterModel_descriptor,
        new String[] { "Message", "ToClientId", "FromServer", "ToServer", });
    internal_static_com_netty_model_protobuf_CommandModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_netty_model_protobuf_CommandModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_netty_model_protobuf_CommandModel_descriptor,
        new String[] { "MessageType", "Data", "Result", "Message", "ClientId", "ServerTime", "DistributeData", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
